--SQLQuery0-CREATE_DATABASE.sql

CREATE DATABASE PV_521_DDL
ON
(
	NAME       = PV_521_DDL,
	FILENAME   = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_521_DDL.mdf',
	SIZE       = 8 MB,
	MAXSIZE    = 512 MB,
	FILEGROWTH = 8 MB
)
LOG ON
(
	NAME       = PV_521_DDL_log,
	FILENAME   = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_521_DDL.ldf',
	SIZE       = 8 MB,
	MAXSIZE    = 512 MB,
	FILEGROWTH = 8 MB
)